# TradeSkills GitHub Pages Configuration
name: "TradeSkills"
description: "A platform for exchanging goods and services without cash"

# GitHub Pages settings
url: "https://rorrimaesu.github.io"  # GitHub Pages URL
baseurl: "/TradeSkills"  # Repository name

# Build settings
permalink: pretty
markdown: kramdown

# SPA settings
plugins:
  - jekyll-seo-tag

# 404 handling
defaults:
  - scope:
      path: ""
    values:
      layout: "default"